#!/usr/bin/env python
# -*- coding: utf-8 -*-
# [Gedit Tool]
# Name=Export to HTML
# Name[fr]=Exporter en HTML
# Shortcut=<Control><Alt>h
# Languages=markdown
# Applicability=all
# Input=document
# Output=new-document
# Save-files=nothing

import codecs
import os
import sys
import markdown
from ConfigParser import SafeConfigParser

# Configuration.
CONFIG_PATH = os.path.expanduser('~') + '/.config/gedit-markdown.ini'
parser = SafeConfigParser()
parser.read(CONFIG_PATH)
markdownVersion = parser.get('markdown-preview', 'version')

text = sys.stdin.read().decode('utf-8')
print "<!-- Markdown => HTML -->"

if markdownVersion == "standard":
	print markdown.markdown(text, smart_emphasis=False).encode('utf-8')
else:
	print markdown.markdown(text, extensions=['extra', 'headerid(forceid=False)']).encode('utf-8')

