#!/usr/bin/env python
# -*- coding: utf-8 -*-
# [Gedit Tool]
# Name=Export to HTML
# Name[fr]=Exporter en HTML
# Shortcut=<Control><Alt>h
# Languages=markdown
# Applicability=all
# Input=document
# Output=new-document
# Save-files=nothing

import codecs
import sys
import markdown

text = sys.stdin.read().decode('utf-8')
print "<!-- Markdown => HTML -->"
print markdown.markdown(text, extensions=['extra', 'headerid(forceid=False)']).encode('utf-8')
