#!/usr/bin/python3
# -*- coding: utf-8 -*-
# [Gedit Tool]
# Name=Export to HTML
# Name[fr]=Exporter en HTML
# Shortcut=<Control><Alt>h
# Languages=markdown
# Applicability=all
# Input=selection-document
# Output=new-document
# Save-files=nothing

import codecs
import os
import sys
import markdown
from configparser import SafeConfigParser

# Configuration.

try:
	import xdg.BaseDirectory
except ImportError:
	homeDir = os.environ.get("HOME")
	xdgConfigHome = os.path.join(homeDir, ".config")
else:
	xdgConfigHome = xdg.BaseDirectory.xdg_config_home

confDir =  os.path.join(xdgConfigHome, "gedit")
confFile =  os.path.join(confDir, "gedit-markdown.ini")
parser = SafeConfigParser()

if os.path.isfile(confFile):
	parser.read(confFile)
	markdownVersion = parser.get("markdown-preview", "version")
else:
	markdownVersion = "extra"

text = sys.stdin.read()
print("<!-- Markdown => HTML -->")

if markdownVersion == "standard":
	print(markdown.markdown(text, smart_emphasis=False))
else:
	print(markdown.markdown(text, extensions=["extra",
	                        "headerid(forceid=False)"]))
